version: "3.8"

services:
  diabet-helper-service_prod:
    build:
      context: .
      dockerfile: diabetHelper_prod.Dockerfile
    ports:
      - "1111:1111"
    container_name: diabet-helper-service_prod
    networks:
      - diabet-helper_prod
#    command: air main.go
    depends_on:
      - diabet-helper-postgres_prod

  diabet-helper-postgres_prod:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    container_name: diabet-helper-postgres_prod
    ports:
      - "5461:5432"
    networks:
      - diabet-helper_prod
    volumes:
      - diabet-helper_postgres:/var/lib/postgresql/data

  diabet-helper-bot_prod:
    build:
      context: .
      dockerfile: diabetHelperBot_prod.Dockerfile
    ports:
      - "1112:1112"
    container_name: diabet-helper-bot_prod
    networks:
      - diabet-helper_prod
#    command: air main.go
    depends_on:
      - diabet-helper-service_prod

networks:
  diabet-helper_prod:
    driver: bridge
    name: diabet-helper_prod

volumes:
  diabet-helper_postgres: